from typing import Protocol
from ..schemas import ExecuteRequest, ExecuteResponse

class AiRuntime(Protocol):
    async def stt(self, request: ExecuteRequest) -> ExecuteResponse: ...
    async def align(self, request: ExecuteRequest) -> ExecuteResponse: ...
    async def tts(self, request: ExecuteRequest) -> ExecuteResponse: ...
    async def nlp(self, request: ExecuteRequest) -> ExecuteResponse: ...
    async def judge(self, request: ExecuteRequest) -> ExecuteResponse: ...
    async def llm(self, request: ExecuteRequest, credential: str | None) -> ExecuteResponse: ...
